version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: music163
    ports:
      - 3333:3306
    environment:
      - LANG=C.UTF-8
      - TERM=dumb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=music163
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
    networks:
      main:
        aliases:
          - music163
networks:
  main: